version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - freecodecamp
networks:
  freecodecamp:
